---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 15m
  chart:
    spec:
      chart: n8n
      version: 9.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    deployment:
      N8N_HOST: "n8n.${BASE_DOMAIN}"
      N8N_EDITOR_BASE_URL: "https://n8n.${BASE_DOMAIN}"

    ingress:
      main:
        enabled: true
        certificateIssuer: tc-le-prod
        ingressClassName:  ""
        hosts:
          - host: n8n.${BASE_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
