clusterName: main
talosVersion: v1.5.5
kubernetesVersion: v1.28.4
endpoint: https://${VIP}:6443
allowSchedulingOnControlPlanes: false
additionalMachineCertSans:
    - ENC[AES256_GCM,data:MsTxAse6,iv:QS4eSq0jseK+CEKoNy5np7PQ27PgcHXSa6ap/yG3X+U=,tag:avdyX1U2Ju5nbyow6Gn8dA==,type:str]
additionalApiServerCertSans:
    - ENC[AES256_GCM,data:fs3gGbpb,iv:Foby6lZhrVMQPZxtUN+aKIWykozFi+PGBmtkFLlvySM=,tag:DqUQeaPdhHi3o7rPb0TXUw==,type:str]
# Warning: Also used in Cilium CNI values!
clusterPodNets:
    - 172.16.0.0/16
clusterSvcNets:
    - 172.17.0.0/16
cniConfig:
    name: none
patches:
    - '@./patches/all.json'
nodes:
    - hostname: k8s-control-1
      ipAddress: ${MASTER1IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cce3
          addresses:
            - ${MASTER1IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-2
      ipAddress: ${MASTER2IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add598b01
          addresses:
            - ${MASTER2IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-3
      ipAddress: ${MASTER3IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cc24
          addresses:
            - ${MASTER3IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-worker-1
      ipAddress: 192.168.10.111
      installDiskSelector:
        size: <= 600GB
controlPlane:
    patches:
        - '@./patches/controlplane.json'
        - '@./patches/sopssecret.yaml'
        - '@./patches/kubePrism.json'
        # schematic:
        #     customization:
        #         # Required when not using enx* mac adress above in networkInterfaces
        #         # extraKernelArgs:
        #         #    - net.ifnames=0
        #         systemExtensions:
        #             officialExtensions:
        #                 # Enable where needed
        #                 # - siderolabs/amd-ucode
        #                 # - siderolabs/bnx2-bnx2x
        #                 # - siderolabs/i915-ucode
        #                 # - siderolabs/intel-ucode
        #                 # - siderolabs/qemu-guest-agent
worker:
    patches:
        - '@./patches/worker.json'
        - '@./patches/kubePrism.json'
        # - '@./patches/nvidia.json'
    schematic:
        customization:
            systemExtensions:
                officialExtensions:
                    # Enable where needed
                    # - siderolabs/amd-ucode
                    # - siderolabs/bnx2-bnx2x
                    - siderolabs/iscsi-tools
                    - siderolabs/qemu-guest-agent
                    # - siderolabs/drbd
                    # - siderolabs/gasket-driver
                    # - siderolabs/i915-ucode
                    # - siderolabs/intel-ucode
                    # - siderolabs/thunderbolt
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3U0JPdGd2WXdBNnZVaGxT
            MUNZMG01a0hYS1hYQzFaWGl0NGhNTy9LREFBCk90S0hTV00xaWRxWTB4d0NsRUlt
            VGZNaXJXMEVZcHZ4UUJtMXdaMnV0NTgKLS0tIGQ5MGlsUXlzSHVZTHJuL3dhNEUw
            OVZDN2cvTU0rNStLS1YycTlBZVFQU1UKC12uBDKqHpVLmLQTGNdeeNrxBhxE9KqM
            ffvuxLq4XNuuXfsHSgIwmw3QXbjbZPYJxxQJYRiIHDQVdzEcY7NVgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-10T11:06:27Z"
    mac: ENC[AES256_GCM,data:bI1Od2tyJ/h1q+JZ22yFmj6ARKtXvIHpRuxOu5rMPzKygInYrPFuiF1PR+Fc7PwcJB5lXC8iPdtyoFWTay38il0rC/oYu03tPdHZUkRfdH32IbjD+gUzFw+1nOxTGYfWuDFNJrEDqE2eh+6MIcU7t/Ah/jicigW8w0uHYplIijY=,iv:D1Pd50xqR6e04l29H5S8E9Mo5IR8XcItdLpq2BbSJTA=,tag:7W3+AkCUNXouIiuZ9a0I0Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
