clusterName: main
talosVersion: v1.6.1
kubernetesVersion: v1.29.0
endpoint: https://${VIP}:6443
allowSchedulingOnControlPlanes: false
additionalMachineCertSans:
    - ENC[AES256_GCM,data:1UK0OREe,iv:QAI76oRfEL2n6KjLxh3In0a8liyaiBOzLo+Lg6rHH+Y=,tag:7GNS+BhiXgxlmtlc2s+01Q==,type:str]
additionalApiServerCertSans:
    - ENC[AES256_GCM,data:FTr4v9Mg,iv:yD8RqWQ8Mmj/Y8qlenlGuZAmJZCJutQqV7myT+PahFo=,tag:uPOeqPDrvKggUv0PmIbgqA==,type:str]
# Warning: Also used in Cilium CNI values!
clusterPodNets:
    - 172.16.0.0/16
clusterSvcNets:
    - 172.17.0.0/16
cniConfig:
    name: none
patches:
    - '@./patches/all.json'
nodes:
    - hostname: k8s-control-1
      ipAddress: ${MASTER1IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cce3
          addresses:
            - ${MASTER1IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-2
      ipAddress: ${MASTER2IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add598b01
          addresses:
            - ${MASTER2IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-3
      ipAddress: ${MASTER3IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cc24
          addresses:
            - ${MASTER3IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-worker-vm-1
      ipAddress: 192.168.10.112
      installDiskSelector:
        size: <= 400GB
    - hostname: k8s-worker-vm-2
      ipAddress: 192.168.10.122
      installDiskSelector:
        size: <= 400GB
    - hostname: k8s-worker-vm-3
      ipAddress: 192.168.10.132
      installDiskSelector:
        size: <= 400GB
controlPlane:
    patches:
        - '@./patches/controlplane.json'
        - '@./patches/sopssecret.yaml'
        - '@./patches/kubePrism.json'
        # schematic:
        #     customization:
        #         # Required when not using enx* mac adress above in networkInterfaces
        #         # extraKernelArgs:
        #         #    - net.ifnames=0
        #         systemExtensions:
        #             officialExtensions:
        #                 # Enable where needed
        #                 # - siderolabs/amd-ucode
        #                 # - siderolabs/bnx2-bnx2x
        #                 # - siderolabs/i915-ucode
        #                 # - siderolabs/intel-ucode
        #                 # - siderolabs/qemu-guest-agent
worker:
    patches:
        - '@./patches/worker.json'
        - '@./patches/kubePrism.json'
        # - '@./patches/nvidia.json'
    schematic:
        customization:
            systemExtensions:
                officialExtensions:
                    # Enable where needed
                    # - siderolabs/amd-ucode
                    # - siderolabs/bnx2-bnx2x
                    - siderolabs/iscsi-tools
                    - siderolabs/qemu-guest-agent
                    # - siderolabs/drbd
                    # - siderolabs/gasket-driver
                    # - siderolabs/i915-ucode
                    # - siderolabs/intel-ucode
                    # - siderolabs/thunderbolt
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYkFHWCtWNXcyNWNzblkv
            bjFaVkhTN2thdTE4d3ozODFLaTVVY1BTclZnCjd2R0RaNklCL0R1cDR0WDZmbU03
            RUFzSkFtYlZwdVo2MW1xMlpEYTB0encKLS0tIGdVQ0ZZZm1DOHBnZlVzUjMvWUgw
            SkxidmdyMnZreGJOWUcxUGhaeXlEZFEKE1w1QiachjfNGivoibrHfsN4TZHnUFEn
            aaIPbpGoXuGDVOvma+ULtRfshrUcyBrqvS3G2emTq/SDpihuz9p6vg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T21:50:37Z"
    mac: ENC[AES256_GCM,data:uq8yHWsclfhFHtTsnA13J4qFNf/g+r0aMgGLfY1CusJPGL8b2CaHsy8eOMpnTOSW4sOSTTCP2gZ07HwglQiFME0gCltZPJcbDcBGpH+O0vZepsLiYa/lcE7m2YCchNv4ZF5UOcpKFTgoqsTBoUujQJ85oCgN5d2lgyKQ/JQ1Kk8=,iv:jb27ECwJPKNpOHtqBeX/g2vP/XkuUBU8Pi9AQYuqhhk=,tag:JflqR6ratlKVFi86+x3KGQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
