clusterName: main
talosVersion: v1.5.5
kubernetesVersion: v1.28.3
endpoint: https://${VIP}:6443
allowSchedulingOnControlPlanes: false
additionalMachineCertSans:
    - ENC[AES256_GCM,data:4jlFqTl3,iv:HGAdRXU60c1fe3wZQ3tqPDxbs7dhBE23N9n9pZ50ZJ8=,tag:J3EhUUBth7ON3Jf4n0eGTA==,type:str]
additionalApiServerCertSans:
    - ENC[AES256_GCM,data:1lN3NgPD,iv:JMDDm/BURxAx91kkD+DjZUK3+nR+myGCA8mn2yX4fKY=,tag:sspYowPHwsZXv3haqMxj0Q==,type:str]
# Warning: Also used in Cilium CNI values!
clusterPodNets:
    - 172.16.0.0/16
clusterSvcNets:
    - 172.17.0.0/16
cniConfig:
    name: none
patches:
    - '@./patches/all.json'
nodes:
    - hostname: k8s-control-1
      ipAddress: ${MASTER1IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cce3
          addresses:
            - ${MASTER1IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-2
      ipAddress: ${MASTER2IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add598b01
          addresses:
            - ${MASTER2IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-control-3
      ipAddress: ${MASTER3IP}
      controlPlane: true
      installDiskSelector:
        size: <= 1TB
      networkInterfaces:
        # suffix is the adapter mac adres.
        - interface: enxd83add59cc24
          addresses:
            - ${MASTER3IP}/24
          routes:
            - network: 0.0.0.0/0
              gateway: ${GATEWAY}
          vip:
            ip: ${VIP}
    - hostname: k8s-worker-1
      ipAddress: 192.168.10.111
      installDiskSelector:
        size: <= 600GB
controlPlane:
    patches:
        - '@./patches/controlplane.json'
        - '@./patches/sopssecret.yaml'
        - '@./patches/kubePrism.json'
        # schematic:
        #     customization:
        #         # Required when not using enx* mac adress above in networkInterfaces
        #         # extraKernelArgs:
        #         #    - net.ifnames=0
        #         systemExtensions:
        #             officialExtensions:
        #                 # Enable where needed
        #                 # - siderolabs/amd-ucode
        #                 # - siderolabs/bnx2-bnx2x
        #                 # - siderolabs/i915-ucode
        #                 # - siderolabs/intel-ucode
        #                 # - siderolabs/qemu-guest-agent
worker:
    patches:
        - '@./patches/worker.json'
        - '@./patches/kubePrism.json'
        # - '@./patches/nvidia.json'
    schematic:
        customization:
            systemExtensions:
                officialExtensions:
                    # Enable where needed
                    # - siderolabs/amd-ucode
                    # - siderolabs/bnx2-bnx2x
                    - siderolabs/iscsi-tools
                    - siderolabs/qemu-guest-agent
                    # - siderolabs/drbd
                    # - siderolabs/gasket-driver
                    # - siderolabs/i915-ucode
                    # - siderolabs/intel-ucode
                    # - siderolabs/thunderbolt
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMnpPOUw1c0s2MklGQTZ0
            Zy9RbTgxT3l4MEhOREs4c3ZmeEdPV2pFRlc4CnczOUR6akg2WlRRbERKVnBzMXVM
            NUFNUW5jOHNkS0hPU0JLV3dKOFBVQU0KLS0tIEpKYmRiRnE5TzVXUlBhbnhFaGVs
            QXgwSTAyajg1ejM2TnROWlp2cmxPMFkKrdc2U1+qpSlq+6aKdcknEov/6ag0bCxm
            f44Ch5sg+NusuYzmlQWHjPsifSW3J/+mzNQh4nWlVAmjioQu3Q+BUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-09T20:44:58Z"
    mac: ENC[AES256_GCM,data:txA9XflV/ILOVJy9TGqriBnTJb8sVD0MQacbRxUauHQ8KYQkEsnyTwzEpHOyz3YR0tc4bQiZy5jNufbaii+9fFXv/Vq2cJd6wlKKWkga6tYSIJncnajKBpZTXCxjMdns2QbZbfUkjSSBewmFXLEe0UWf1XGHj6J1GEVYwUm8m/I=,iv:lF5pRNsbe6LmOTqwgMfm9luDwzEuaq4AFkSUF021Y/M=,tag:XnTsSIBuZKnI4kXFFDK9kg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
