apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    VIP: ENC[AES256_GCM,data:v4Z/bbLARqpcXtO8EjM=,iv:dmCwk5GHgE1xybb/Ljq8/ODwCF2RiLb5E8cxPQsHn0k=,tag:51sL3V+LpxLktMYtohU0Tg==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:I3p3c/yLmrds/zR7lko=,iv:0D4t6GR6BRfpJY9oUur+WZb4e8it7JNI0+LjL4y17qk=,tag:IZvjL+4nI4pI0LelxgdtfA==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:7j2mBOTcFJxzSoX/AzM=,iv:rfTfntA7PObqnZyTPiiWaYVo7BYYMOmiiRZXkdQxRJE=,tag:w5EJPlFXrjF3Cu9khgjirQ==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:Gsk3WZjCgdN8jTZJcec=,iv:5DD351Igj+WwL0K0rbgxjnddY09dFJGwoQReZvbhHdA=,tag:LCUUxNw2kmxbu/kZDOwNQw==,type:str]
    GATEWAY: ENC[AES256_GCM,data:hrIU4t9nALHYKI2W,iv:mKIAOpZEwe35qX7vpZq+jykSR8CGXkxzC1U2NR9IhnE=,tag:TzswWelgoA6UAw1a6lAIqA==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:UArz8+EMDaVn6xSEA7gPkufj3MS/sxnyH36hud4=,iv:b21ZTSoDiX+Rg+fkZQMCjuAlISiiPwf7/ELlGwF0Ry4=,tag:M5j+/tOArhyP6sBlapceeQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:leFh+WaTz+fGSzaSQKg=,iv:W9qS/BhMZw8xDxwHCm3PXvwZUe5/hx6BWQkmxKmMGqw=,tag:VG0oUeKRvFgkTdMln5IVbw==,type:str]
    BASE_DOMAIN2: ENC[AES256_GCM,data:Z8eIbzV9nVKoee/NCyQ=,iv:DTqYK52fZ9X/oWreAwUJ6CFKtZlU0UU24Wv76ipwnyg=,tag:+qck5TGoBPgefqomYIWFuw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:rkAWbvWVoIXX6QVUeu4=,iv:D9dFiYYg//Bi+XJk7RXb8XPD2aunN2XR5mO+bGqJszA=,tag:ry12pGsNQMe4UXF1RNOGaQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:TA/BO9+0a2c9fouQtFw=,iv:2PE4bwtFN7Mflt2N2fIlEJFgK9qf5Qde0hw8zdsDs8A=,tag:BrNXqFDVUE2owwQc6zaxtQ==,type:str]
    EMAIL: ENC[AES256_GCM,data:ENy/aQdXfUGvTKl6Sg/E8cg8SA==,iv:6Eb4RB3FeFjuKBb7PlxcJJJv9fFGJJrfsIw4teDw2iA=,tag:5QruJx6vEi8wZunpuL5wgg==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:iErJ4fAVsc7bwGmDfZdS88CQriQjDLujoHofmPzY64XexTY9MIrHAQ==,iv:vwDbDf6qVWnouLYzCWxABVRcFwrIsAMVk17J7m4f/YM=,tag:bHXC1J0ofnilJFIutRwVOg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:/hKNItDoR2QkBo/LzCTLu1YBrGBtEpuQzBqltUkQgfSjKTBobFQDww==,iv:9LTx+zj4gEePBv9229zSUtY3dPc8kLyJDHEpPj59YZM=,tag:7iYFiCRRBLIO9R+lD7hFKw==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:pAJN7Lzklt4Sog==,iv:HV9LQBi1JCCqhOW91aoKDpF//dZMHtdDAe9Ah5ApJA4=,tag:Lh73DkANWIWOFHt7m9ZUWQ==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:La05uUazOmN3JS9A5G3gYd6/,iv:gFq3NGqXaIeT4vHrhSPTVwKKCO2e8gwpvcYlbvj9ZsY=,tag:hqZYfH0sOY5CqFzKY155GA==,type:str]
    EMAIL2: ENC[AES256_GCM,data:C4pKRmfJyBfe+OtolG4ey7SBtL/V,iv:W6j7N4wnn1CCULus7uhyQVMVfuY8ipuGYs/Vlu6kl4k=,tag:jryg85ZdNb+G5CCXlMFUYA==,type:str]
    CLOUDFLARE_TOKEN2: ENC[AES256_GCM,data:tB/eXPMGBLy8fC7ORQAxlvaj/8Qb6bv+I4RxljALjx0PgFyeW85KAg==,iv:kYrQPpxSI9rmvi51if9ETqpnJwU80uwf+0YluVY/E9Q=,tag:TcpEK0+F1PC1BhlVWZGdug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsblRZZ2NjMkw3SVVwcHFu
            cWNCTkJZVkpwRmdmbG53VDRHc2lCaGRSYlhVCnVHdmNycjdJZXR6bkJIUWdxNkJq
            QzIrdmJjQTB5cDVYRzc5SVk1VDArVlkKLS0tIGlqZWRUV0tCVEVxMHZhKzNnQ2RN
            WEpKdFlpUkJIbW1OaVRZS3NaUGJ6M0UKAVH2/M59RTpYcrhEXBgDiwtzTj151phS
            Ca+fn/4cfutXpdlvsxM5QmtsRj6cVrNAjf7oOw0J1xTVozPMWUOfmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-24T21:50:35Z"
    mac: ENC[AES256_GCM,data:DA8s7WTB3fEqgkRFuzuqiqSFcdmLcsx0pB0R/ikFUV57KKozC2auSnGZD2UeC5XITVsbkGoIr6DnwDJqVjKilpgfld3gwGdeNRFqZlWzUFwECxllqUjRv/DBk1GCshUDXvu4T+/5QRq4QdTdRpJtFptCBf6uQ99JsEKetn3Qnoo=,iv:4frnEmQhzszR2VAaK2GYXXsDOmmnys+ix8RVC0yPLNo=,tag:leNsY3RT4QR2ON1l+GPw+Q==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
