apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    VIP: ENC[AES256_GCM,data:B++/rK7vAXaOWz4ukuQ=,iv:iA5uIJK6R4FXfX8L13cA9r0Fw106R1a3UyyJXD5K3BI=,tag:K64dcVQWiKCzkqeMxqjN9A==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:wUZr8cufpzuZ3sohxR4=,iv:gldTA26nddRAQDtx2FEEi6nxA6jJDV7N3EqrQgy1oTA=,tag:cjrtEbEneZf0uWrZny/Dew==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:w4kY+R1VWasan9EJxO0=,iv:KfHgbigkLoHWtidWQTjoxq+H3d9XrZNbnm7E+1fDamM=,tag:bTZgDNzJg6ELAS47p+ZUxA==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:HEDAkXwR1Gn4gI/VIBc=,iv:Xoix84ku2LTozt3Rz0B3na9JnWpASEdkYMEOIjd327Y=,tag:pXLAfNnHGg6pykxlSk9ZEA==,type:str]
    GATEWAY: ENC[AES256_GCM,data:dGQMYmYhMj9bIZGw,iv:CwxF6RaK+HNkqy+JRk0VquU8uPZTf4TvpqM7CLpUy+M=,tag:JX5ywrrs46jzRTFSeynFQQ==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:D4yt9vv1EgMFr0Js5VuBcIhdRTl6XW5bIlqdGSw=,iv:olScRyvM+IkyOicHb1jrh8qF04sGTgaSPC3xJUwJVOc=,tag:Gik130PPSuRmxokX37+GIw==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:bFce8WSdI8iSPcB+Gmw=,iv:VL3Oiri9Zqha8k3qpMhxH0+1LGXhBJjfwRQ5dpA/TZE=,tag:9mRv63br69BqtyMhgWXBDA==,type:str]
    Blocky_IP: ENC[AES256_GCM,data:41nBl7/Gdv9VGMzy33A=,iv:oTWqOAnz07ehIG1PpiEIw9uXrkyUD3wA3F5732JIK2E=,tag:JHDPni+DrDMfkezFzyCgrQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:1vGu7pq7m2z5J/uDSfY=,iv:kKumLTZugFoHbqtWGF4N/ERj1loLgNSVMITo8m6tV0A=,tag:eP1kifkCTM2pjoudwspS5Q==,type:str]
    EMAIL: ENC[AES256_GCM,data:O9uikAXNnH65uMCTk891AwI3sw==,iv:FFMByfhK4l0Rcg/D6RxpL6fhGGrUCL98VCyJw2wb8LQ=,tag:L1BiMypa/pCqrmzOGnJLYA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:kSlejqiQlSPQszc=,iv:ecRB6txM++EIm0fNNBSahjfhWFxrEBHSdyfsG/iJwmQ=,tag:kPJ7YQrNlMvWsw9lb6HeuQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:ymBnuYZai1PI9LpK4K+I823kt06cx6U49Xp6tnv50wN4A8Rn4POlUA==,iv:/ZMqYSbnviMjrHxF8k9FcAolX/IBmJX4D/dcrcBOr/8=,tag:xZ1JxAAMSI2mhLXut4viDQ==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:+zFGJEOER2Fqmg==,iv:ZaPD8+qCfrVx9TZyYx7/bjbcTlewyovydTiTCRSmYjo=,tag:v96MIlnv5G5sK4ojD9hsyA==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:92Css6jzne9Qr7Od2PDAkxxb,iv:ad7tfLteRx+VlPZovNvERNnJyhcIaI8Qt1/eWi8UfYw=,tag:uGieaS56r85i0LxssqODzw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTanEwNFV0Yzl2SzdQSDBY
            anRUeis1cFJyNFdTRVFkZVJsdG5hTHJORXdjCnQ5REVZYlFTbHFSbmxWTnF1aWtL
            NmI2THcrWHJyYTVHSjhxSWl4aXRUYkUKLS0tICthN3RrMEM0SSs1bWxNYlo1ekll
            NHp2MWptYjIyVGNuT3VqZ0FiVmJMeGMKQybufhFDIvqNRZB8sXLYe6qO/W3hNlC8
            PJh0uBOfyENTf0kEqgCsqO9NUhDj7AEkLFDh+4J6LuCVecvlMhNQsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-26T00:21:48Z"
    mac: ENC[AES256_GCM,data:vroFgNUO7wh/1KvVR9K8+l/t4ndK0TcT/c8vKGRLCi52QBcp0OABR1z05YXzL9TygauA1H1lkNOwVtKw/e2CAwvWv0Odi9WK2yQDoHZFFxX4mCy0Vn77vT/zxPMsrbO8hQXl4OVNTjlDsswy22qUZ8GzOgLGKyAmmBO0TGbg5Qs=,iv:BoqOzxgsLbW7ypq1Gm1etCzL1jbRAQg835WrAGg5Qns=,tag:BrbAL0gnD29v1UfhSe1DqA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
