apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    VIP: ENC[AES256_GCM,data:7BV09EvNxnE6WyNQwNs=,iv:gbxq0sHrt7aDRl5n6mYc8Wxw63S0N/Ytu33ZPnHScRc=,tag:/PwD7N4mhsTPlwy28+nzkg==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:tkFIDdEVzWQlIa7PuAM=,iv:Y/+aRqODJWCFAtcR+SW3rKpLbpO+c4oPgMz2yYJG214=,tag:VGRpFZ42o/B9QFmYrAX5Xg==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:HgKyfsIPa9litCxFKIg=,iv:JBaqbw9IvQfJNHiZlCZCCYwYSztkEBiPwL3c115RvDs=,tag:rWy9NrG2h4xo8JeLVaOomQ==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:U/NNL0YRXhtO5kYatho=,iv:hwlr0msyxXjg2hhquJWqu9MwNwHE50qb0b1wvBz6Zvg=,tag:Z7Rxporr5xdtnEOYvQbvKg==,type:str]
    GATEWAY: ENC[AES256_GCM,data:RQy13hr0kwNtFau6,iv:4u+iDY8zu+qBrtzJKG88W6pA1J2tyKJcyUN8wQVIcCQ=,tag:F6y230GDJRkYS/HdQms0Wg==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:GFCHi8VBW56DX/bGQas27hDRw1QnXQbA/V/souA=,iv:YWkLcsGttoVtv10jzi+tuR148tAIC1Gxw5l0qEVJNR4=,tag:yGWxMSMRRBbOTtjO30dT6g==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:Lf2UBdEF4IgxQocPvgw=,iv:Dg9OZNh7gYBJaJIj0U1wp3++b21klObwA+Ffc2ZJHI4=,tag:+Pzcjh/E2h4zukG0vivdBg==,type:str]
    BASE_DOMAIN2: ENC[AES256_GCM,data:h3Edwm2hWS2zGrMl0CFWhw==,iv:pTn6TXQajYL4jD54Tw+rMBiliK466eLJfld5luWWHw8=,tag:1fG6jQ5HsgSfSrAOE4DGRQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:FzungVdO+FYWTMU1G/c=,iv:3vAGZV22ea8gIol7okfTGNwFVLyeOM9HOBNY2MtSIOQ=,tag:NrsTPQOjI0baraYi/y7pDQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:50XKgXyODOXBWw1hpg4=,iv:15QvUXnw68HcIAQ+ZGmGln53dAp+xt51uP1K9CdNgYY=,tag:J4eUIrdtJkO2kUbdu71o6w==,type:str]
    EMAIL: ENC[AES256_GCM,data:A/exEAjfZOI+UeO+3YOXchMmOg==,iv:uW95DRE1CnU41TL8r0OAWp9AIUlBb9lC1q5YmiTdsXk=,tag:PMMLnK4W9+2qoDl2RuwxxQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:TPhAV2nAIvm913PhtFcND2Tcur+AseUTf9c+RCt4cQCQXuxL7DHDPA==,iv:GfYwtbiWMPOW8DcWFESxBmUftXwhGjP1qSCDWS1HFkQ=,tag:S9JbNVa6Rj386++JtKpYmg==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:VnXRIagqeSMDdoQmBtNvhBgTDhON5iSjqyotFYvrHl4MWc/5+qk8gw==,iv:JTpHDV760E8NJwBHZW8u2k4jlMAQVT0AFn/Ftcz67uk=,tag:G0P5nzNqjA32kKGGFDK2uQ==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:lR67WIzOyGuZQw==,iv:mnfUXzEC1o5y4d43V2tVXw9cHZaVj4G/S8tbFum0UrE=,tag:AYFmOCaqNdFdK/++4fD90A==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:x1+gEX+ytyoLUE8dPZTEHs9e,iv:3VKZOSBfRcCup3PaCFFfzs/uhuDcauzNQWQy3Om72VU=,tag:1/UhamJW9+nXP+Tka9e4FA==,type:str]
    EMAIL2: ENC[AES256_GCM,data:2GrK+OyTYc3h71riIJ4QI1dY8A/5,iv:Lj+98T/45goMBBxsPITKqDtdc8sib0ftMVTEzCjs9LI=,tag:Lq5J0CRQmOmhRe9O+7HVjg==,type:str]
    CLOUDFLARE_TOKEN2: ENC[AES256_GCM,data:+IsNVKJOBbpUA5d3NqH8WovQ6klt+JUcbzWNDXDUhi3pdNlgxYfUsA==,iv:UqDyN9eD+ucxZ+AOXsSGwjPKhrmvMLKjTHG6dL3kO1Q=,tag:Qd1ws+haQ3XTfqjlVznoCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WFB6TnRGNlhkbDA4Ymh4
            NVlWQ2UwQTMvR0UxL2U3ekRWZk1XZmZwQUdvCkJ5emZNbkhLbUJaVTE5a2FkK0xC
            azU2T2ZPVXFVMkRWb2JBS284V0s1alUKLS0tIGlLVVV4ZWRpRzNuU3BJN1ovK1V6
            ejU0S3l3eVZLSm92UWJ6NFNDZWZTSlkKzfZK3NHE6zHjm1Hqwl/VYHw8+BZSR6oN
            1XPxBg1VnE+IMiE50GtZIOB/5ZOsK0MgbtsRpCOcBtCBcHyZ23V5tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-27T16:11:58Z"
    mac: ENC[AES256_GCM,data:4iFhpIhSrL8GW9y8+elBc7Tlyuyaxp6HBfCTjMbyCecvJHwzWh+bmWz+a5eqH69jwIjNX5MhHhog31VP2TmO8gu3dnC+2kwGPmZSzg4X4JOoyuLGvW6NYq+s8lrgyNqlg3znc8YSkWS9AjECG0e2An78ejeIKVsS+1yGUBEuPmI=,iv:jxle0fPGQlzcmvzbJ492fT9m4TbRKg0WaRL7SufVvy8=,tag:OZjt3NENQyPp7DGg6x42Pg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
