apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    VIP: ENC[AES256_GCM,data:qxJc/fAcXSccGElmzRo=,iv:W61AA98ZUuX51gDEe4MSnXEMnkfYyIvnoP6ktKNVwco=,tag:3aVgMC466/3Zri/TIldDTQ==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:pf+g9Sva9DhYPo0kC1U=,iv:zQ7plQ4uKM2qcd9LOyjqmnLoPcdY/rnBoWWRkYWvb6I=,tag:MoxtjqM66n7P0+SbyJTlXQ==,type:str]
    MASTER2IP: ENC[AES256_GCM,data:bzJV5Vd0hn2hUNYPSFY=,iv:1Ff2FGsnm0LmirqDbX/WeTQ4FySj9SDuRcdYRqdI3es=,tag:DmCGgb6BDuu233z8uQBuHw==,type:str]
    MASTER3IP: ENC[AES256_GCM,data:oASdozNaLfzSirExOsk=,iv:QUuXU0pVBtfcNCK5Y6IuZ1MLzDefLYSaz0EwWY9+u30=,tag:ZKIRgz47ZwB1XcLD2FeqPg==,type:str]
    GATEWAY: ENC[AES256_GCM,data:IWzwvd7+HMXdTBcz,iv:Df2JhBq4IIElKSCW9spstv7QLXhYuQpOQR/hLSqzAGA=,tag:Ww/rs9oWnyZq5+JTlkUXsA==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:Kv8TPfy72n6GFZopz1BE6GM7NLUoRIxZVnQhHzo=,iv:zJUPbUwiVMkD0/QH5n4tS9YSRUJnLc+SQ5BLqLz0Zok=,tag:i7p7yjMmEhu7enaVXLPZ7Q==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:kmC2/eKk1fWGPWLM4T8=,iv:j+iR9qNJxT0FYGIO+WHrPLd+eurtyclFl/QzSL5Mc24=,tag:WUPOQ8pEIaL/1x66juO1dw==,type:str]
    BASE_DOMAIN2: ENC[AES256_GCM,data:aD6Hm+ppwTcPPsjwaUX/Rw==,iv:0PxuUMrnZNWnR56RgKNdRAz+tSalLL7ljcm2qr2vyhA=,tag:K9i139cUcXE8Ta5ryGckEw==,type:str]
    BASE_DOMAIN3: ENC[AES256_GCM,data:wUp0Ff8pJifxKTTQSw==,iv:JDPQej6Jpa6K75QWJonWsVA4r0/shJZqzyFK6NthLrg=,tag:VMcOzwLhBjkYWSPvlLOAlw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:R2Z3Jisxlck3ArTblW8=,iv:vNq06LxjyFPRgtXl4bRyDmb/7CFrNSxDgbxQqjD/FW4=,tag:4n4xygJY++8qsfi2eY4yTw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:y0AzEV5QBVO/fqsUlYc=,iv:yprMPXtygRrtolL2qTsBPL/p3u84dh8USNk+1TxEwKM=,tag:k8h0TOA79ZRqgflNQbZaFQ==,type:str]
    PLEX_IP: ENC[AES256_GCM,data:9FJJ1imYebkid0FGkyU=,iv:jxPoFZIsjMXcyf1KW7/xazqRUH8zY6B67TXKH2f+Dsk=,tag:pbj2B1a1VoZ5Z7nc0Mt1lg==,type:str]
    KMS_IP: ENC[AES256_GCM,data:c7TbzqEL6gKtgyX9kkk=,iv:/b7SOHWZ1xsE9kJIaBSwh/Hj7azQohm81U3vz+jdfTM=,tag:RrrZ1ViTn9dyIWF7vjL43w==,type:str]
    EMAIL: ENC[AES256_GCM,data:DKqUaCiFitMNYuHmJTc5AfRX7g==,iv:4a41EST4k0ZDHE+puQI8e9V420fsx/uai7Y+y0eK7n8=,tag:x8JN6ZGB87+mkJCr7qLr6w==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:SdNT5dl8prigJ+70Nxwf1i6X0xL2y8wy41RIzxupxHPy8VbvhNiZDA==,iv:TVyU7tO12iD8+6eEe/j+AgsWSqarqxgs0ELwCe/3+tY=,tag:7TRp0IG2+adJzI0A364LcQ==,type:str]
    GITHUB_TOKEN: ENC[AES256_GCM,data:1r4tcXk7yzQqrboOUGzAWZXpQAxtqReA7pi+C0zzW7al3wNnXaFvVQ==,iv:tZ2DTNJ8kkyiAhdK1iAC/3NtRULLdziMnyNItHqOdHg=,tag:AbvA7NN/uXYP1FMN5p33Sw==,type:str]
    GITHUB_USER: ENC[AES256_GCM,data:y18J23XNjxmweg==,iv:An40Ct5HCfTseBgJWrDPK3voThsUgPtODqla1sUm+7M=,tag:VvCb3cYGbLuPbchAQbsixA==,type:str]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:fbMXG9XNhYgctbAJgpLKlHBF,iv:MmVoubdzmO0BDDumKVNoiVMeWcjcs8hZyqMxPm0oYSM=,tag:naw7Vln22wqmCxKoHtKtdw==,type:str]
    EMAIL2: ENC[AES256_GCM,data:vSIDkoqAf0GF8X4aFMMwguxChkP4,iv:6aU0ETw4etl9XQbbvbSB43CMLr2rDz59dLgHzfc0Wi0=,tag:2s5BOjKgTkYkZLPRoH29dA==,type:str]
    CLOUDFLARE_TOKEN2: ENC[AES256_GCM,data:+bVj2LFO5I/9RWyAZiaH8u8nZ4Bs4OxYfJvdY2P+ZQALZZ0rU8ydyw==,iv:pgQMwpPv9QTodz8MigUuAtMlUc1dQmngL7KIrUxqoE0=,tag:hUHy46aYHYEgK9uyWaG/oQ==,type:str]
    EMAIL3: ENC[AES256_GCM,data:n8EbJdQTFJ3yWxDv9wEQi1oe,iv:AFAKEF+saV6kIud0PcNeuHAukpukYj6amXxe7/psCOQ=,tag:8gcOJzs/+Bejy6cIPJjtXw==,type:str]
    CLOUDFLARE_TOKEN3: ENC[AES256_GCM,data:DAfawcsR97vioD6ulilfGIT2bNjUQ0VMBAuwrntYu98WGaYfgIkv5A==,iv:+Yr2/xpRSY+Ds37e/nJc1x136woLBCAE72YF+XKkdgQ=,tag:YQQMWj+jeJ7S2U7098KJmw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzy27yg04slm0t4naapemy207fd7uh4lda70dxnh932e5dd8n55skgcdrq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc25pNllEd1lvR2VLaU8w
            WkFSM2V6U3g3NW1xU2ZnT1dIS2R3S0o5b1FnCkRGc2doSndpUmtleDJMelh0NVk0
            V2VUUlVJQStWSkR5eTZEN0tDeTV1YmsKLS0tIHlmVGRuZmJuTjBneUd4TnU3NE1U
            NXBIRVNlRHp3NTRzbzduV0UycUI3bWsKkAPAUVNSAajPsBzoRqFKRSfhOjfDR8zU
            2KVf8841qx2WOeEV8Ix+ydlNhti9G8EbY2tVKmvZ9DLBkW98eV0k1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-05T12:24:25Z"
    mac: ENC[AES256_GCM,data:lWazz1TXyt47F+5BltK4f3X2ku5omWlFiFnFjGBUkrMO/nWb5fiLI55i+kn+xl+r+PQfO+sXOnO7Va+VutjLvhBXEGKHcESTdcNrMh0kXgVpf2RceH0BDgNtLS20k+AVJLBRNKTKy3xb+r3K5dryG9lOkDwkW0Jp3KRMue6p5YY=,iv:l9iGt0zrnOtRoPk5s7MVZBsLP29M1YMCkkoSwvtC6/w=,tag:3MzPDqNJMXwK+YTEN0Bl4w==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.8.1
