---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kubeapps
    repo: oci://registry-1.docker.io/bitnamicharts/kubeapps
    version: 2.9.0
    releaseName: kubeapps
    namespace: kubeapps
    valuesFile: values.yaml
commonAnnotations:
  meta.helm.sh/release-name: kubeapps
  meta.helm.sh/release-namespace: kubeapps
commonLabels:
  app.kubernetes.io/managed-by: Helm
